# GENERATED by bindings/python/tools/generate_models.py — DO NOT EDIT.
# Source: .agent-team/04-architecture/api-contracts.md contract: blocks (TYPE-1..7).
# Rerun the generator when the contract changes; tests/python/test_models.py asserts
# this file is byte-identical to a fresh generation (manual edits cannot hide).
# Wire convention: payload enums are internally tagged {"kind": "<Variant>"};
# fieldless enums are plain strings (see generator docstring).
from __future__ import annotations

from typing import Annotated, Any, Literal, Union

from pydantic import BaseModel, ConfigDict, Field, StringConstraints

# Frozen at the type level: Python cannot mutate boundary data (data-model-erd §5).
# extra="forbid": fields beyond the contract are boundary violations (FFI-SCHEMA).
_FROZEN = ConfigDict(frozen=True, extra='forbid', populate_by_name=True)

# --- TYPE-1 identifiers (string/int mirrors; only Sha256Hex has a stated format invariant) ---
SessionId = Annotated[str, StringConstraints(pattern=r"^[0-7][0-9A-HJKMNP-TV-Z]{25}$")]
RunId = Annotated[str, StringConstraints(pattern=r"^[0-7][0-9A-HJKMNP-TV-Z]{25}$")]
CorrelationId = Annotated[str, StringConstraints(pattern=r"^[0-7][0-9A-HJKMNP-TV-Z]{25}$")]
EnvelopeId = Annotated[str, StringConstraints(pattern=r"^[0-7][0-9A-HJKMNP-TV-Z]{25}$")]
NodeId = str
Sha256Hex = Annotated[str, StringConstraints(pattern=r"^[0-9a-f]{64}$")]
CommitSeq = int
WaveIndex = int

class Payload(BaseModel):
    model_config = _FROZEN
    schema_id: str
    json_: Any = Field(alias='json')

class Message(BaseModel):
    model_config = _FROZEN
    role: Literal["system", "user", "assistant", "tool"]
    content: str
    tool_call_id: str | None = None

class ToolDef(BaseModel):
    model_config = _FROZEN
    name: str
    description: str
    parameters_schema: Any

class ToolCall(BaseModel):
    model_config = _FROZEN
    id: str
    name: str
    arguments: Any

class ToolResult(BaseModel):
    model_config = _FROZEN
    call_id: str
    content: Any
    taint: Annotated[Union[TaintClean, TaintTainted], Field(discriminator="kind")]

class CacheBreakpoints(BaseModel):
    model_config = _FROZEN
    stable: int
    context: int
    volatile: int

class LlmRequest(BaseModel):
    model_config = _FROZEN
    messages: list[Message]
    temperature: float | None = None
    max_tokens: int | None = None
    tools_schema: list[ToolDef]
    cache_breakpoints: CacheBreakpoints

class LlmReply(BaseModel):
    model_config = _FROZEN
    content: str
    tool_calls: list[ToolCall]
    tokens_in: int
    tokens_out: int
    provider_meta: dict[str, Any]

class TaintClean(BaseModel):
    model_config = _FROZEN
    kind: Literal["Clean"] = "Clean"


class TaintTainted(BaseModel):
    model_config = _FROZEN
    kind: Literal["Tainted"] = "Tainted"
    source: Any  # TaintSource has no defining block in api-contracts — opaque


Taint = Annotated[Union[TaintClean, TaintTainted], Field(discriminator="kind")]

# --- PY-1 hesmos.Session / hesmos.Budget ---
# --- PY-2 hesmos.Plan.from_yaml ---
# --- PY-3 @core.provider(model_ref) — LLM 콜백 등록 ---
# --- PY-4 @core.tool(name) — 도구 콜백 등록 (MCP 포함) ---
# --- PY-5 core.run(plan, task, dry_run=False) -> RunReceipt ---
# --- PY-6 예외 계층 ---
# --- PY-7 프롬프트 빌더·deferred 명령 (캐시 불변식 Python 측) ---
# --- PY-8 메모리·스킬 (선언형) — Should ---
# --- CLI-1 hesmos run <plan> [--seed <u64>] [--budget <spec>] [--dry-run] ---
# --- CLI-2 hesmos trace show <session_id> [--gate] [--handoff] [--limit N] [--json] ---
# --- CLI-3 hesmos trace replay <session_id> [--at step <N>] ---
# --- CLI-4 hesmos budget [<session_id>] [--team <team_id>] [--json] ---
# --- CLI-5 hesmos eval <suite> [--bless <session_id>] [--json] ---
# --- CLI-6 hesmos serve [--bind <addr>] [--port <n>] ---
# --- FFI-1 hesmos-ffi PyO3 표면 ---
# --- HTTP-1 GET /api/sessions ---
# --- HTTP-2 GET /api/sessions/{id} · GET /api/sessions/{id}/events ---
# --- HTTP-3 WS /api/sessions/{id}/stream ---
# --- HTTP-4 GET /api/budgets?team_id={team_id} ---
# --- HTTP-5 GET /api/audit/{session_id} · 공통 에러 본문 ---
# --- PORT-1 EventSink ---
# --- PORT-2 BathosEngine ---
# --- TYPE-2 Envelope ---
class Envelope(BaseModel):
    model_config = _FROZEN
    id: EnvelopeId
    from_: NodeId = Field(alias='from')
    to: NodeId
    kind: Literal["Task", "Result", "Control", "Knowledge"]
    payload: Payload
    correlation_id: CorrelationId
    taint: Annotated[Union[TaintClean, TaintTainted], Field(discriminator="kind")]

# --- TYPE-3 TraceEvent ---
EventKind = Literal["SessionOpen", "SessionClose", "PlanCompiled", "GatePass", "GateFail", "NodeStart", "NodeStop", "HandoffRequest", "HandoffAccept", "LlmCall", "ToolCall", "BudgetEvent", "TraceSeal"]

class TraceEvent(BaseModel):
    model_config = _FROZEN
    seq: int
    kind: EventKind
    node: NodeId | None = None
    attrs: dict[str, Any]
    prev_hash: Sha256Hex
    hash: Sha256Hex

# --- TYPE-4 HandoffContract ---
class HandoffContract(BaseModel):
    model_config = _FROZEN
    goal_original: str
    goal_current: str
    invariants: list[str]
    done_criteria: Any
    artifacts: list[Any]
    failed_approaches: list[Any]
    assumptions: list[Any]
    confidence: Annotated[float, Field(ge=0.0, le=1.0)]
    from_node: NodeId
    to_node: NodeId | None = None
    permission_cap: Any
    snapshot: SnapshotSlice

class SnapshotSlice(BaseModel):
    model_config = _FROZEN
    goal_original: str
    prev_contract_summary: str
    node_input: Payload
    shared_knowledge: list[Any]

# --- TYPE-5 SessionHandle ---
SessionState = Literal["Init", "Running", "Suspended", "Halted", "Completed", "Cancelled", "Failed"]

class SessionHandle(BaseModel):
    model_config = _FROZEN
    session_id: SessionId
    run_id: RunId
    seed: int
    plan_hash: Sha256Hex
    budget: BudgetEnvelope
    state: SessionState
    team_id: str | None = None
    fork_of: tuple[SessionId, CommitSeq] | None = None
    chain_head: Sha256Hex | None = None

# --- TYPE-6 Plan / StageSpec / AgentProfile / BudgetEnvelope / PolicySet ---
class Plan(BaseModel):
    model_config = _FROZEN
    name: str
    task: str
    team_id: str | None = None
    pattern: Literal["Sequential", "Parallel", "Swarm", "Graph"]
    stages: list[StageSpec]
    edges: list[Any]
    budget: Any
    knowledge: Any
    policy_overrides: Any

class StageSpec(BaseModel):
    model_config = _FROZEN
    id: NodeId
    profile: AgentProfile
    input_schema: str
    done_criteria: Any
    gates: Any
    is_terminal: bool
    is_router: bool

class AgentProfile(BaseModel):
    model_config = _FROZEN
    role: str
    model: str
    temperature: float | None = None
    tools: list[str]
    resource_limits: Any
    network: Any
    spawn_token_floor: int

class BudgetEnvelope(BaseModel):
    model_config = _FROZEN
    session_max_tokens: int | None = None
    team_max_tokens: int | None = None
    agent_max_tokens: dict[str, int]
    warn_pct: int
    suspend_pct: int

# --- TYPE-7 GateVerdict / RouteDecision / CompileError / HesmosError ---
class GateVerdictPass(BaseModel):
    model_config = _FROZEN
    kind: Literal["Pass"] = "Pass"
    score: float

class GateVerdictRetry(BaseModel):
    model_config = _FROZEN
    kind: Literal["Retry"] = "Retry"
    reason_code: Literal["MAX_HANDOFFS", "TIMEOUT", "REPETITIVE_HANDOFF", "BUDGET_EXCEEDED", "GATE_REJECT", "PROVIDER_FAILURE"]
    score: float
    attempts_left: int

class GateVerdictReject(BaseModel):
    model_config = _FROZEN
    kind: Literal["Reject"] = "Reject"
    reason_code: Literal["MAX_HANDOFFS", "TIMEOUT", "REPETITIVE_HANDOFF", "BUDGET_EXCEEDED", "GATE_REJECT", "PROVIDER_FAILURE"]
    score: float

GateVerdict = Annotated[Union[GateVerdictPass, GateVerdictRetry, GateVerdictReject], Field(discriminator='kind')]

class RouteDecisionAccept(BaseModel):
    model_config = _FROZEN
    kind: Literal["Accept"] = "Accept"
    to: NodeId
    contract_hash: Sha256Hex

class RouteDecisionReturnToSender(BaseModel):
    model_config = _FROZEN
    kind: Literal["ReturnToSender"] = "ReturnToSender"
    reason_code: Literal["MAX_HANDOFFS", "TIMEOUT", "REPETITIVE_HANDOFF", "BUDGET_EXCEEDED", "GATE_REJECT", "PROVIDER_FAILURE"]
    contract_hash: Sha256Hex

class RouteDecisionRetryBounded(BaseModel):
    model_config = _FROZEN
    kind: Literal["RetryBounded"] = "RetryBounded"
    reason_code: Literal["MAX_HANDOFFS", "TIMEOUT", "REPETITIVE_HANDOFF", "BUDGET_EXCEEDED", "GATE_REJECT", "PROVIDER_FAILURE"]
    attempts_left: int

class RouteDecisionHalt(BaseModel):
    model_config = _FROZEN
    kind: Literal["Halt"] = "Halt"
    reason_code: Literal["MAX_HANDOFFS", "TIMEOUT", "REPETITIVE_HANDOFF", "BUDGET_EXCEEDED", "GATE_REJECT", "PROVIDER_FAILURE"]

RouteDecision = Annotated[Union[RouteDecisionAccept, RouteDecisionReturnToSender, RouteDecisionRetryBounded, RouteDecisionHalt], Field(discriminator='kind')]

class CompileErrorSchemaParse(BaseModel):
    model_config = _FROZEN
    kind: Literal["SchemaParse"] = "SchemaParse"
    location: Any

class CompileErrorUnknownNodeRef(BaseModel):
    model_config = _FROZEN
    kind: Literal["UnknownNodeRef"] = "UnknownNodeRef"
    node: Any
    refs: Any

class CompileErrorCyclicDependency(BaseModel):
    model_config = _FROZEN
    kind: Literal["CyclicDependency"] = "CyclicDependency"
    cycle: Any

class CompileErrorInvalidDsl(BaseModel):
    model_config = _FROZEN
    kind: Literal["InvalidDsl"] = "InvalidDsl"
    expression: Any

class CompileErrorMissingGoalOriginal(BaseModel):
    model_config = _FROZEN
    kind: Literal["MissingGoalOriginal"] = "MissingGoalOriginal"

class CompileErrorProfileMissing(BaseModel):
    model_config = _FROZEN
    kind: Literal["ProfileMissing"] = "ProfileMissing"
    node: Any

class CompileErrorPatternNormalizationFailed(BaseModel):
    model_config = _FROZEN
    kind: Literal["PatternNormalizationFailed"] = "PatternNormalizationFailed"
    reason: Any

class CompileErrorDuplicateNodeId(BaseModel):
    model_config = _FROZEN
    kind: Literal["DuplicateNodeId"] = "DuplicateNodeId"
    node: Any

class CompileErrorInvalidBudgetSpec(BaseModel):
    model_config = _FROZEN
    kind: Literal["InvalidBudgetSpec"] = "InvalidBudgetSpec"

CompileError = Annotated[Union[CompileErrorSchemaParse, CompileErrorUnknownNodeRef, CompileErrorCyclicDependency, CompileErrorInvalidDsl, CompileErrorMissingGoalOriginal, CompileErrorProfileMissing, CompileErrorPatternNormalizationFailed, CompileErrorDuplicateNodeId, CompileErrorInvalidBudgetSpec], Field(discriminator='kind')]

class HesmosError(BaseModel):
    model_config = _FROZEN
    class_: Literal["Reason", "Compile", "Platform", "Usage", "Ffi"] = Field(alias='class')
    code: str
    session_id: SessionId | None = None
    node_id: NodeId | None = None
    message: str
    hint: str | None = None

# --- TRAIT-1 Stage ---
# --- TRAIT-2 GraphEngine ---
# --- TRAIT-3 Gate ---
# --- TRAIT-4 HandoffRouter ---
EVENT_ATTRS_REQUIRED: dict[str, dict[str, Any]] = {
    "SessionOpen": ["session_id", "seed", "budget", "team_id_opt"],
    "SessionClose": ["session_id", "final_state", "reason_code_opt"],
    "PlanCompiled": ["plan_hash", "node_count"],
    "GatePass": ["gate_id", "score"],
    "GateFail": ["gate_id", "reason_code", "score"],
    "NodeStart": ["node_id", "agent_role", "wave"],
    "NodeStop": ["node_id", "agent_role", "wave", "stop_kind"],
    "HandoffRequest": ["contract_hash", "from", "to_opt"],
    "HandoffAccept": ["contract_hash", "from", "to"],
    "LlmCall": ["provider", "model", "tokens_in", "tokens_out", "latency_ms"],
    "ToolCall": ["tool_name", "ok", "latency_ms", "actor"],
    "BudgetEvent": ["level", "spent", "remaining"],
    "TraceSeal": ["chain_head_hash"],
}

EVENT_ATTRS_OPTIONAL: dict[str, dict[str, Any]] = {
    "GatePass": ["judge.prompt_hash", "judge.temperature", "judge.model_version"],
    "GateFail": ["judge.prompt_hash", "judge.temperature", "judge.model_version", "judge.verdict"],
}

# TYPE-4 field_absence_matrix — T4 reject oracle (api-contracts TYPE-4)
FIELD_ABSENCE_MATRIX: dict[str, str] = {
    "goal_original": "compile_error",
    "goal_current": "reject",
    "invariants": "reject",
    "done_criteria": "reject_no_retry",
    "artifacts": "post_gate_fail",
    "failed_approaches": "warn_proceed",
    "assumptions": "reject",
    "confidence_below_threshold": "bounded_retry",
}

REASON_CODES = ("MAX_HANDOFFS", "TIMEOUT", "REPETITIVE_HANDOFF", "BUDGET_EXCEEDED", "GATE_REJECT", "PROVIDER_FAILURE")

